name: metro-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.2
  - pandas=2.1.4
  - scikit-learn=1.3.2
  - pytest=7.4.3
  - pip:
    - Flask==3.0.0
    - Flask-RESTful==0.3.10
    - Flask-CORS==4.0.0
    - Flask-SQLAlchemy==3.1.1
    - Werkzeug==3.0.1
    - pymysql==1.1.0
    - SQLAlchemy==2.0.23
    - onnxruntime==1.16.3
    - python-dotenv==1.0.0
    - marshmallow==3.21.0
    - schedule==1.2.0
    - APScheduler==3.10.4
    - gunicorn==21.2.0
    - black==23.11.0
    - flake8==6.1.0